# Generated by Django 4.2.2 on 2023-07-03 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('copies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rent', models.DateTimeField(default=None)),
                ('date_limit', models.DateTimeField(default=None)),
                ('date_devolution', models.DateTimeField(default=None)),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copies.copy')),
            ],
        ),
    ]
