# Generated by Django 4.2.2 on 2023-07-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0003_alter_rent_date_devolution_alter_rent_date_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='date_devolution',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='date_limit',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='date_rent',
            field=models.DateField(auto_now_add=True),
        ),
    ]
