# Generated by Django 4.2.2 on 2023-07-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
